# Simple convolutional NN based classifier of German road traffic signs

# Import libraries
import streamlit as st
from PIL import Image, ImageOps
import cv2

# Set up the basic md for the webpage that will be generated by streamlit

st.title("German Traffic Sign Classifier")
st.header("German Traffic Sign Classifier")
st.text("Upload A German Traffic Sign: ")
st.text("Sample images are here to download: ")

from sign_classifier import sign_classifier

# Import the image to be classified:

uploaded_file = st.file_uploader("Choose a traffic sign ...", type="jpg")
if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption='Uploaded traffic sign.', use_column_width=True)
    st.write("")
    st.write("Classifying...")
    # Call the trained CNN based model to classify the image
    label = sign_classifier(image,'traffic.h5')    
    st.write(label)

  
